### ISSUE TITLE
SpaceAfter=No not marked on many sentences with no space after them according to #text

### ISSUE THREAD

**Issue by AngledLuffa** [UniversalDependencies/UD_Arabic#2]
For example:

```
# sent_id = ummah.20040531.0026:p3u2
# text = دهعملاب راشتسملا دمحأ ىفطصم روتكدلا كلذ نلعأ.
...
8       دهعملا  دهَعمَ    NOUN    N------S2D      Case=Gen|Definite=Def|Number=Sing       6       nmod    6:nmod:بِ:gen    Vform=دِهَعمَلاَ|Gloss=institute|Root=`_h_d|Translit=al-maʿhadi|LTranslit=maʿhad
9       .       .       PUNCT   G---------      _       1       punct   1:punct Vform=.|Translit=.
```

This could very well be an ignorance of Arabic, since I know almost nothing about the language.  However, I would expect either line 8 to have SpaceAfter=No in this sentence, or for the text to have a space before the final period. 

If this is indeed a data issue, there are many such sentences in PADT.  I can volunteer to send a list of all of them, or to edit the file if you tell me which of the two changes are needed.  Thanks!

**Comment by dan-zeman** [comment]
I am not sure what happened but when I search the sentence id in the data, I get a different sentence text and different FORM and LEMMA on line 8. Nevertheless, the rest of annotation on line 8 matches your excerpt, including the Translit and LTranslit attributes (which contain transliteration of my FORM and LEMMA, not the ones you have on that line).

Anyways, the part you omitted and replaced by "..." is crucial for understanding why the CoNLL-U of this sentence is actually correct:

<pre>
# sent_id = ummah.20040531.0026:p3u2
# text = أعلن ذلك الدكتور مصطفى أحمد المستشار بالمعهد.
# orig_file_sentence UMH_ARB_20040531.0026#4
1	أعلن	أَعلَن	VERB	VP-A-3MS--	Aspect=Perf|Gender=Masc|Number=Sing|Person=3|Voice=Act	0	root	0:root	Vform=أَعلَنَ|Gloss=announce,declare|Root=`_l_n|Translit=ʾaʿlana|LTranslit=ʾaʿlan
2	ذلك	ذلك	X	U---------	_	1	obj	1:obj	Vform=ذلك|Root=OOV|Translit=ḏlk
3	الدكتور	دُكتُور	NOUN	N------S1D	Case=Nom|Definite=Def|Number=Sing	5	nmod	5:nmod:nom	Vform=اَلدُّكتُورُ|Gloss=doctor|Root=d_k_t_r|Translit=ad-duktūru|LTranslit=duktūr
4	مصطفى	مصطفى	X	U---------	_	5	nmod	5:nmod	Vform=مصطفى|Root=OOV|Translit=mṣṭfī
5	أحمد	أحمد	X	U---------	_	6	nmod	6:nmod	Vform=أحمد|Root=OOV|Translit=ʾaḥmd
6	المستشار	مُستَشَار	NOUN	N------S1D	Case=Nom|Definite=Def|Number=Sing	1	nsubj	1:nsubj	Vform=اَلمُستَشَارُ|Gloss=counselor,adviser|Root=^s_w_r|Translit=al-mustašāru|LTranslit=mustašār
7-8	بالمعهد	_	_	_	_	_	_	_	SpaceAfter=No
7	ب	بِ	ADP	P---------	AdpType=Prep	8	case	8:case	Vform=بِ|Gloss=by,with|Root=bi|Translit=bi|LTranslit=bi
8	المعهد	مَعهَد	NOUN	N------S2D	Case=Gen|Definite=Def|Number=Sing	6	nmod	6:nmod:بِ:gen	Vform=اَلمَعهَدِ|Gloss=institute|Root=`_h_d|Translit=al-maʿhadi|LTranslit=maʿhad
9	.	.	PUNCT	G---------	_	1	punct	1:punct	Vform=.|Translit=.

</pre>

Word no. 8 is part of a multi-word token 7-8. Since it is the multi-word token what appears on the surface, the `SpaceAfter=No` tag must appear (and does appear) on the 7-8 line.

The correspondence between the text attribute and SpaceAfter=No in MISC is checked by the [UD validation script](https://github.com/UniversalDependencies/tools/blob/master/validate.py). This is not to say that the script is guaranteed to be error-free; but if a genuine error in SpaceAfter=No is found in a released UD treebank, then it means that there must be an error in the official validation.

**Comment by AngledLuffa** [comment]
Ah, thanks so much for the patient explanation.  It did not occur to me
that the SpaceAfter label would only be on the MWT and not the last word.

As for the different text, it is entirely possible I copy/pasted pieces of
two different examples I had found.  More evidence that I have no ability
to read Arabic, I'm afraid.
